@baseAddress = http://localhost:5155

GET {{baseAddress}}/api/categories
Accept: application/json

###


POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "category 12"
}

###


GET {{baseAddress}}/api/categories
Accept: application/json

###
